spring.application.name=springboot.practice
server.port = 8080

#MY_SQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=rajat123@
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto= update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Spring Security Configuration ---> Commented as we are moving to InMemoryUserDetailsManager
#spring.security.user.name=rajat
#spring.security.user.password=rajat

#404 error configuarion
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

app.secret.key = d1b9e078f244199859f5f62497645f782c3c6f145b5971a1796c738f3224213d

#spring.sql.init.data-locations=sql/data-schema.sql

#Loggin configuration
logging.level.root = INFO
#Package level logging
#logging.level.com.rajat.springboot.practice = ERROR
#logging.group.app_error = com.rajat.springboot.practice.controller
#logging.level.app_error = WARN

#File level logging
#logging.file.name=logs/blogapp.log
#logging.pattern.file={"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","logger":"%c","message":"%m"}
